# Generated by Django 5.2.8 on 2025-11-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
