# Generated by Django 5.2.8 on 2025-11-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='image',
            new_name='itemimage',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='itemname',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='price',
            new_name='itemprice',
        ),
    ]
