# Generated by Django 5.2.8 on 2025-11-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_image_menu_itemimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='itemimage',
            field=models.ImageField(upload_to='mnu/'),
        ),
    ]
