# Generated by Django 5.2.8 on 2025-11-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_menu_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='itemimage',
            field=models.ImageField(upload_to='menu/'),
        ),
    ]
