# Generated by Django 5.2.8 on 2025-11-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='itemprice',
            field=models.IntegerField(),
        ),
    ]
