# Generated by Django 5.2.8 on 2025-11-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
