# Generated by Django 5.2.8 on 2025-11-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='special',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
