# Generated by Django 5.2.8 on 2025-11-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_specialoffer_delete_offer_combo_menuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
