# Generated by Django 5.2.8 on 2025-11-28 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_combooffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialoffer',
            name='items',
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_offers', to='myapp.menu'),
        ),
    ]
