# Generated by Django 5.2.8 on 2025-11-28 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_specialoffercart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboOfferCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.combo')),
            ],
        ),
    ]
