# Generated by Django 5.2.8 on 2025-11-29 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_order_date_order_combo_order_special_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combooffer',
            name='image',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='combooffercart',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.combo'),
        ),
        migrations.AlterField(
            model_name='specialoffercart',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.specialoffer'),
        ),
    ]
