# Generated by Django 5.2.8 on 2025-12-02 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0024_combooffer_image_alter_combooffercart_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combooffercart",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.combooffer",
            ),
        ),
    ]
