# Generated by Django 5.2.8 on 2025-12-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0025_alter_combooffercart_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
