# Generated by Django 5.2.8 on 2026-02-06 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_register_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='id',
            new_name='kh_id',
        ),
    ]
