from django.urls import path
from myapp import views
urlpatterns = [
    path('',views.index),
    path('register/',views.register),
    path('login/', views.login),
    path('adminp/', views.admin),
    path('kitchenhandler/',views.kitchenhandler),
    path('vieworders/',views.vieworders),
    path('kitchenhandlerindex/',views.kitchenhandlerindex),
    path('menu/',views.menu),
    path('add_to_cart/<id>/<qn>/', views.add_to_cart, name='add_to_cart'),
    path('add_combo_cart/<int:id>/<int:qn>/', views.add_combo_cart, name='add_combo_cart'),
    path('get_cart_count/', views.get_cart_count, name='get_cart_count'),
    path('delete_cart/<int:cart_id>/', views.delete_cart, name='delete_cart'),
    path('delete_combo_cart/<int:cart_id>/', views.delete_combo_cart, name='delete_combo_cart'),
    path('delete_special_cart/<int:cart_id>/', views.delete_special_cart, name='delete_special_cart'),
    path('make_order/',views.make_order),
    path('update_order_status/<int:order_id>/', views.update_order_status, name='update_order_status'),
    path('confirm_order/',views.confirm_order),
    path('payment/',views.payment),
    path('submit/',views.submit),
    path('email/',views.email),
    path('otp/',views.otp),
    path('password/',views.password),
    path('delete/<id>/',views.delete_menu),
    path('sales/',views.sales),
    path('specialoffer/', views.add_special_offer, name='add_special_offer'),
    path('', views.manage_menu_page, name='view_menu'),
    path('addcombo/', views.add_combo_offer, name='add_combo_offer'),
    path('combooffer/',views.combooffer),
    path('special_offer/',views.specialoffer),
    path('logout/', views.logout),
    path('orders/', views.orders),

    ]